version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    restart: unless-stopped
    ports:
      - "5000:5000"  # <--- host:container
    networks:
      - webnet

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"  # <--- host:container
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

