name: Deploy to Azure VM

on:
  push:
    branches:
      - master  # or main if you use main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup SSH key
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}

    - name: Deploy via SSH
      env:
        AZURE_SSH_USER: ${{ secrets.AZURE_SSH_USER }}
        AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}
      run: |
        ssh -o StrictHostKeyChecking=no $AZURE_SSH_USER@$AZURE_VM_IP << 'EOF'
          cd "$HOME/skravops/" || exit
          git pull origin master
          docker compose down
          docker compose up -d --build
        EOF

